title: Discover and reuse projects within your organization
tagline: High level yet impactful innersource concepts to help transform your organization.
description: Organizations of all sizes and in all industries are chatting about innersource concepts. This course walks you through some of the key concepts of innersource and helps you build up an internal toolkit for adopting innersource practices. 
template:
  name: innersource
  repo: innersource-template
before:
- type: createIssue
  title: Welcome
  body: 00_welcome.md
- type: updateBranchProtection

# Course artifacts:
# 1. Issue: Welcome
# 2. PR: Repository ownership and names
# 3. PR: Create discoverable repos
# 4. PR: Issue and PR templates
# 5. PR: Workflows
# 6. PR: Managing projects on GitHub
# 7. PR: Measuring success
# 8: Issue: Publish your toolkit

steps:

#1
- title: Answer your first challenge question
  description: Determine the differences between open source and innersource.
  link: '{{ repoUrl }}/issues/1'
  event: issues.edited
  actions:
  - type: createPullRequest
    title: Repository ownership and names
    head: repo-owner
    body: 01_repo-owner.md
    action_id: ownerPR
  - type: respond
    with: 01_innersource-v-opensource.md
    data: 
      url: '%actions.ownerPR.data.html_url%'
  - type: closeIssue


#2
- title: Answer the ownership challenge
  description: Discover how repository ownership affects visibility and access.
  link: '{{ repoUrl }}/pull/2'
  event: pull_request.edited
  actions:
  - type: removeBranchProtection
  - type: respond
    with: 02_repo-owner-answer.md

#3
- title: Merge the ownership pull request
  description: Beef up your innersource toolkit with resources about repository ownership.
  link: '{{ repoUrl }}/pull/2'
  event: pull_request.closed
  actions:
  - type: updateBranchProtection
  - type: createPullRequest
    title: Create discoverable repos
    head: discoverable-repos
    body: 03_discoverable.md
    action_id: discoverablePR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.discoverablePR.data.html_url%'  

#4
- title: Answer the discoverability challenge
  description: Learn about ways to make your repository easy to discover.
  link: '{{ repoUrl }}/pull/3'
  event: issue_comment.created
  actions:
  - type: removeBranchProtection
  - type: respond
    with: 04_discoverability-answer.md

#5
- title: Merge the discoverability pull request
  description: Add resources for making discoverable repositories to your innersource toolkit.
  link: '{{ repoUrl }}/pull/3'
  event: pull_request.closed
  actions:
  - type: updateBranchProtection
  - type: createPullRequest
    title: Issue and PR templates
    head: templates
    body: 05_templates.md
    action_id: templatesPR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.templatesPR.data.html_url%'

#6
- title: Answer the templates challenge question
  description: Determine how template files can help you create easy-to-join projects.
  link: '{{ repoUrl }}/pull/4'
  event: pull_request.edited
  actions:
  - type: removeBranchProtection
  - type: respond
    with: 06_templates-answer.md

#7
- title: Merge the templates pull request
  description: Add starter templates to your innersource toolkit.
  link: '{{ repoUrl }}/pull/4'
  event: pull_request.closed
  actions:
  - type: updateBranchProtection
  - type: createPullRequest
    title: Workflows
    head: workflows
    body: 07_workflows.md
    action_id: workflowsPR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.workflowsPR.data.html_url%'

#8
- title: Answer the workflows challenge question
  description: Discover how being transparent about your workflow can help others contribute.
  link: '{{ repoUrl }}/pull/5'
  event: pull_request.edited
  actions:
  - type: removeBranchProtection
  - type: respond
    with: 08_workflows-answer.md

#9
- title: Merge the workflows pull request
  description: Add branching and workflow strategies to your innersource toolkit.
  link: '{{ repoUrl }}/pull/5'
  event: pull_request.closed
  actions:
  - type: updateBranchProtection
  - type: createPullRequest
    title: Managing projects on GitHub
    head: projects
    body: 09_projects.md
    action_id: projectsPR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.projectsPR.data.html_url%'

#10 
- title: Answer the project management challenge
  description: Learn about how you can surface your project management strategies to potential contributors.
  link: '{{ repoUrl }}/pull/6'
  event: pull_request.edited
  actions:
  - type: removeBranchProtection
  - type: respond
    with: 10_projects-answer.md

#11
- title: Merge the project management pull request
  description: Beef up your innersource toolkit with project management tips.
  link: '{{ repoUrl }}/pull/6'
  event: pull_request.closed
  actions:
  - type: updateBranchProtection
  - type: createPullRequest
    title: Measuring success
    head: metrics
    body: 11_metrics.md
    action_id: metricsPR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.metricsPR.data.html_url%'

#12
- title: Answer the success metrics challenge
  description: Begin thinking about how to measure the success of your innersource program.
  link: '{{ repoUrl }}/pull/7'
  event: issue_comment.created
  actions:
  - type: removeBranchProtection
  - type: respond
    with: 12_metrics-answer.md

#13
- title: Merge the metrics pull request
  description: Add possible metrics to your innersource toolkit.
  link: '{{ repoUrl }}/pull/7'
  event: pull_request.closed
  actions:
  - type: updateBranchProtection
  - type: createIssue
    title: Publish your toolkit
    body: 13_publish.md
    action_id: publishIssue
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.publishIssue.data.html_url%'

#14
- title: Enable GitHub Pages
  description: Publish your innersource toolkit by turning on GitHub Pages. 
  link: '{{ repoUrl }}/pull/8'
  event: deployment
  actions:
  - type: removeBranchProtection
  - type: respond
    issue: Publish your toolkit
    with: 14_congratulations.md
    data:
      deploymentURL: 'https://%payload.repository.owner.login%.github.io/%payload.repository.name%'
      learningPathURL: 'https://github-learning-lab-staging.herokuapp.com/githubtraining/paths/innersource:-theory-to-practice'
      forkURL: '%payload.repository.html_url%/fork'
      downloadURL: '%payload.repository.html_url%/archive/master.zip'